CREATE TABLE IF NOT EXISTS t_p86624112_golden_legacy_academ.site_content (
    id SERIAL PRIMARY KEY,
    key VARCHAR(100) UNIQUE NOT NULL,
    value TEXT NOT NULL,
    updated_at TIMESTAMP DEFAULT NOW()
);

INSERT INTO t_p86624112_golden_legacy_academ.site_content (key, value) VALUES
  ('hero_title_line1', 'Золотое'),
  ('hero_title_line2', 'Наследие'),
  ('hero_subtitle', 'Пять ступеней мастерства, которые превратят ваш опыт в вечное наследие. Система наставничества, проверенная временем.'),
  ('hero_badge', '✦ Академия Наставничества ✦'),
  ('hero_btn_start', 'Начать обучение'),
  ('hero_btn_login', 'Войти в кабинет'),
  ('stat_graduates', '247'),
  ('stat_grounds', '5'),
  ('stat_years', '12'),
  ('grounds_section_title', 'Пять Площадок Мастерства'),
  ('grounds_section_subtitle', 'Каждая ступень открывается после успешного завершения предыдущей'),
  ('about_title_line1', 'Место, где опыт'),
  ('about_title_line2', 'становится наследием'),
  ('about_text', 'Мы создали систему, в которой каждый эксперт может структурировать свои знания, передать их следующему поколению и оставить след, который будет жить в людях.'),
  ('about_img_caption', 'Пространство, созданное для роста'),
  ('contacts_email', 'info@zolotoe-nasledie.ru'),
  ('contacts_phone', '+7 (800) 000-00-00'),
  ('contacts_address', 'Москва, ул. Примерная, 1'),
  ('contacts_telegram', '@zolotoe_nasledie'),
  ('footer_text', 'Академия Золотое Наследие'),
  ('ground1_title', 'Основы наставничества'),
  ('ground1_subtitle', 'Фундамент мастерства'),
  ('ground1_description', 'Базовые принципы наставничества, философия передачи знаний и установление доверия с подопечными.'),
  ('ground2_title', 'Психология роста'),
  ('ground2_subtitle', 'Искусство понимания'),
  ('ground2_description', 'Глубинная психология развития личности, мотивация и раскрытие потенциала каждого ученика.'),
  ('ground3_title', 'Методы передачи знаний'),
  ('ground3_subtitle', 'Технологии обучения'),
  ('ground3_description', 'Авторские методики, инструменты наставника и создание персональных программ развития.'),
  ('ground4_title', 'Лидерство и влияние'),
  ('ground4_subtitle', 'Сила примера'),
  ('ground4_description', 'Развитие лидерских качеств, построение репутации эксперта и расширение круга влияния.'),
  ('ground5_title', 'Мастер-наставник'),
  ('ground5_subtitle', 'Вершина мастерства'),
  ('ground5_description', 'Создание собственной школы наставничества, подготовка наставников и формирование наследия.')
ON CONFLICT (key) DO NOTHING;
